import { BarMenuI } from '../interfaces';

export const BarMenu: BarMenuI[] = [
  {
    name: 'Main',
    nameRu: 'Главная',
    link: '',
    linkRu: '',
    isRoute: true,
    state: false,
  },
  {
    name: 'React Regalo',
    nameRu: 'React Ассистент',
    link: 'https://regalo-margarita.web.app/',
    linkRu: 'https://regalo-margarita.web.app/',
    isRoute: false,
    target: '_blank',
    state: false,
  },
  {
    name: 'Vue Charts',
    nameRu: 'Vue графы',
    link: 'https://char-ts.web.app/',
    linkRu: 'https://char-ts.web.app/',
    isRoute: false,
    target: '_blank',
    state: false,
  },
  {
    name: 'NgRx Pong',
    nameRu: 'NgRx Понг',
    link: 'pong',
    linkRu: 'pong',
    target: '_blank',
    state: false,
  },
  {
    name: 'Fire Congrats',
    nameRu: 'Поздравления',
    link: 'https://fire-cong.web.app/',
    linkRu: 'https://fire-cong.web.app/',
    isRoute: false,
    target: '_blank',
    state: false,
  },
  {
    name: 'Birthday',
    nameRu: 'День рождения',
    link: 'https://birth-cong.web.app/',
    linkRu: 'https://birth-cong.web.app/',
    isRoute: false,
    target: '_blank',
    state: false,
  },
  {
    name: 'Experiment',
    nameRu: 'Эксперимент',
    link: 'https://candy-poll.web.app/',
    linkRu: 'https://candy-poll.web.app/',
    isRoute: false,
    target: '_blank',
    state: false,
  },
  {
    name: '(reserved)',
    nameRu: '(ожидает)',
    link: '',
    linkRu: '',
    isRoute: true,
    state: false,
  },
  {
    name: 'Resume (ENG)',
    nameRu: 'Резюме (RU)',
    link: 'assets/resume/resume.pdf',
    linkRu: 'assets/resume/resume-ru.pdf',
    download: 'resume.pdf',
    target: '_blank',
    state: false,
  },
];
